name: Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install tools
        run: brew install bats-core shfmt shellcheck

      - name: Format code
        run: ./scripts/format.sh

      - name: Run all checks
        run: ./scripts/check.sh
