name: Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install tools
        run: brew install bats-core shfmt shellcheck

      - name: Check formatting
        run: ./scripts/format.sh --check

      - name: Run shellcheck
        run: |
          find . -type f \( -name "*.sh" -o -name "mole" \) \
            ! -path "./.git/*" \
            -exec shellcheck -S warning {} +

      - name: Run tests
        run: tests/run.sh
